// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protofiles

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatserviceClient is the client API for Chatservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatserviceClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (Chatservice_ChatClient, error)
}

type chatserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatserviceClient(cc grpc.ClientConnInterface) ChatserviceClient {
	return &chatserviceClient{cc}
}

func (c *chatserviceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (Chatservice_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &Chatservice_ServiceDesc.Streams[0], "/chatservice/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatserviceChatClient{stream}
	return x, nil
}

type Chatservice_ChatClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chatserviceChatClient struct {
	grpc.ClientStream
}

func (x *chatserviceChatClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatserviceChatClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatserviceServer is the server API for Chatservice service.
// All implementations must embed UnimplementedChatserviceServer
// for forward compatibility
type ChatserviceServer interface {
	Chat(Chatservice_ChatServer) error
	mustEmbedUnimplementedChatserviceServer()
}

// UnimplementedChatserviceServer must be embedded to have forward compatible implementations.
type UnimplementedChatserviceServer struct {
}

func (UnimplementedChatserviceServer) Chat(Chatservice_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedChatserviceServer) mustEmbedUnimplementedChatserviceServer() {}

// UnsafeChatserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatserviceServer will
// result in compilation errors.
type UnsafeChatserviceServer interface {
	mustEmbedUnimplementedChatserviceServer()
}

func RegisterChatserviceServer(s grpc.ServiceRegistrar, srv ChatserviceServer) {
	s.RegisterService(&Chatservice_ServiceDesc, srv)
}

func _Chatservice_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatserviceServer).Chat(&chatserviceChatServer{stream})
}

type Chatservice_ChatServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type chatserviceChatServer struct {
	grpc.ServerStream
}

func (x *chatserviceChatServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatserviceChatServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Chatservice_ServiceDesc is the grpc.ServiceDesc for Chatservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chatservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatservice",
	HandlerType: (*ChatserviceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _Chatservice_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protofiles/bi-directional_streaming.proto",
}
